#pragma once

#define CAPACITY_TO_BYTES(CAPACITY) ((CAPACITY + 1) / 8)
#define INDEX_TO_BYTES(INDEX) (INDEX >> 3)
#define INDEX_TO_OFFSET(INDEX) (INDEX & 0x7)
#define OFFSET_TO_MASK(OFFSET) (1 << OFFSET)
