#pragma once

#define DC_BITSET_STATIC_CAPACITY_TO_BYTES(CAPACITY) ((CAPACITY + 7ULL) / 8ULL)
#define DC_BITSET_STATIC_INDEX_TO_BYTES(INDEX) (INDEX >> (uint8_t)3)
#define DC_BITSET_STATIC_INDEX_TO_OFFSET(INDEX) (INDEX & 0x7)
#define DC_BITSET_STATIC_OFFSET_TO_MASK(OFFSET) (uint8_t)((uint8_t)1 << (uint8_t)OFFSET)
