#pragma once

#define DC_BITSET_STATIC_CAPACITY_TO_BYTES(CAPACITY) ((CAPACITY + 7) / 8)
#define DC_BITSET_STATIC_INDEX_TO_BYTES(INDEX) (INDEX >> 3)
#define DC_BITSET_STATIC_INDEX_TO_OFFSET(INDEX) (INDEX & 0x7)
#define DC_BITSET_STATIC_OFFSET_TO_MASK(OFFSET) (1 << OFFSET)
