#include <derive-cpp/test/gtest_panic.hpp>
#include <gtest/gtest.h>

extern "C" {
#include <derive-c/container/arena/chunked/utils.h>
}

TEST(ArenaChunkedUtils, IndexToBlock) {
    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_BLOCK(0, 1), 0);
    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_BLOCK(1, 1), 0);
    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_BLOCK(2, 1), 1);
    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_BLOCK(3, 1), 1);

    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_BLOCK(0, 3), 0);
    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_BLOCK(7, 3), 0);
    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_BLOCK(8, 3), 1);
}

TEST(ArenaChunkedUtils, IndexToOffset) {
    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_OFFSET(0, 1), 0);
    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_OFFSET(1, 1), 1);
    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_OFFSET(2, 1), 0);
    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_OFFSET(3, 1), 1);

    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_OFFSET(0, 3), 0);
    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_OFFSET(7, 3), 7);
    EXPECT_EQ(DC_ARENA_CHUNKED_INDEX_TO_OFFSET(8, 3), 0);
}

TEST(ArenaChunkedUtils, BlockSize) {
    EXPECT_EQ(DC_ARENA_CHUNKED_BLOCK_SIZE(0), 1);
    EXPECT_EQ(DC_ARENA_CHUNKED_BLOCK_SIZE(1), 2);
    EXPECT_EQ(DC_ARENA_CHUNKED_BLOCK_SIZE(2), 4);
}

TEST(ArenaChunkedUtils, BlockOffsetToIndex) {
    EXPECT_EQ(DC_ARENA_CHUNKED_BLOCK_OFFSET_TO_INDEX(0, 0, 0), 0);
    EXPECT_EQ(DC_ARENA_CHUNKED_BLOCK_OFFSET_TO_INDEX(0, 0, 31), 0);

    EXPECT_EQ(DC_ARENA_CHUNKED_BLOCK_OFFSET_TO_INDEX(0, 7, 3), 7);
    EXPECT_EQ(DC_ARENA_CHUNKED_BLOCK_OFFSET_TO_INDEX(1, 0, 3), 8);
    EXPECT_EQ(DC_ARENA_CHUNKED_BLOCK_OFFSET_TO_INDEX(1, 1, 3), 9);
}
